{
    "101": { "Class" : "actuator", "Type" : "switch/level0", "Model" : "SWITCH-LV0", "Name" : "스위치Lv0", "CommSpec" : { "KS X 3267" : { "read" : { "items": ["opid", "status", "remain-time"] } } } }, 
    "102": { "Class" : "actuator", "Type" : "switch/level1", "Model" : "SWITCH-LV1", "Name" : "스위치Lv1", "CommSpec" : { "KS X 3267" : { "read" : { "items": ["opid", "status", "remain-time"] }, "write" : {"items": ["operation", "opid", "hold-time"] } } } }, 
    "103": { "Class" : "actuator", "Type" : "switch/level2", "Model" : "SWITCH-LV2", "Name" : "스위치Lv2", "CommSpec" : { "KS X 3267" : { "read" : { "items": ["opid", "status", "remain-time", "ratio"] }, "write" : { "items": ["operation", "opid", "hold-time", "ratio"] } } } }, 
    "111": { "Class" : "actuator", "Type" : "retractable/level0", "Model" : "MOTOR-LV0", "Name" : "개폐기Lv0", "CommSpec" : { "KS X 3267" : { "read" : { "items": ["opid", "status", "remain-time"] } } } }, 
    "112": { "Class" : "actuator", "Type" : "retractable/level1", "Model" : "MOTOR-LV1", "Name" : "개폐기Lv1", "CommSpec" : { "KS X 3267" : { "read" : { "items": ["opid", "status", "remain-time"] }, "write" : { "items": ["operation", "opid", "time"] } } } }, 
    "113": { "Class" : "actuator", "Type" : "retractable/level2", "Model" : "MOTOR-LV2", "Name" : "개폐기Lv2", "CommSpec" : { "KS X 3267" : { "read" : { "items": ["opid", "status", "remain-time", "position"] }, "write" : { "items": ["operation", "opid", "time", "position", "open-time", "close-time"] } } } },
    "201": { "Class" : "actuator", "Type" : "nutrient-supply/level0", "Model" : "NUT-LV0", "Name" : "양액기Lv0", "CommSpec" : { "KS X 3288" : { "read" : { "items": ["opid", "status", "area", "alert", "remain-time"] } } } }, 
    "202": { "Class" : "actuator", "Type" : "nutrient-supply/level1", "Model" : "NUT-LV1", "Name" : "양액기Lv1", "CommSpec" : { "KS X 3288" : { "read" : { "items": ["opid", "status", "area", "alert", "remain-time"] }, "write": {"items":["operation", "opid"]} } } }, 
    "203": { "Class" : "actuator", "Type" : "nutrient-supply/level2", "Model" : "NUT-LV2", "Name" : "양액기Lv2", "CommSpec" : { "KS X 3288" : { "read" : { "items": ["opid", "status", "area", "alert", "remain-time"] }, "write": { "operations": [ { "opcode" : 401, "items":["operation", "opid"] }, { "opcode" : 402, "items":["operation", "opid", "start-area", "stop-area", "time"] }, { "opcode" : 404, "items":["operation", "opid", "area-bitmap", "time"] } ] } } } }, 
    "204": { "Class" : "actuator", "Type" : "nutrient-supply/level3", "Model" : "NUT-LV3", "Name" : "양액기Lv3", "CommSpec" : { "KS X 3288" : { "read" : { "items": ["opid", "status", "area", "alert", "remain-time"] }, "write": { "items":["operation", "opid", "start-area", "stop-area", "time", "EC", "pH"] } } } },
    "205": { "Class" : "actuator", "Type" : "nutrient-supply/level4", "Model" : "NUT-LV4", "Name" : "양액기Lv4", "CommSpec" : { "KS X 3288" : { "read" : { "items": ["opid", "status", "area", "alert", "remain-time"] }, "write": { "operations": [ { "opcode" : 401, "items":["operation", "opid"] }, { "opcode" : 402, "items":["operation", "opid", "start-area", "stop-area", "time"] }, { "opcode" : 403, "items":["operation", "opid", "start-area", "stop-area", "time", "EC", "pH"] }, { "opcode" : 404, "items":["operation", "opid", "area-bitmap", "time"] }, { "opcode" : 405, "items":["operation", "opid", "area-bitmap", "time", "EC", "pH"] } ] } } } }, 
    "301": { "Class" : "actuator", "Type" : "fnd", "Model" : "FND display", "Name" : "디스플레이", "CommSpec" : { "KS X 3267" : { "read" : { "items": ["opid", "status"] }, "write" : { "operations": [{ "opcode": 0, "items": ["operation", "opid"] }, { "opcode": 501, "items": ["operation", "opid", "value", "sig-digit"] }, { "opcode": 502, "items": ["operation", "opid", "epoch", "tz-offset"] }, { "opcode": 503, "items": ["operation", "opid", "short"] }] } } } }
}
