{
    "1": { "Class" : "sensor", "Type" : "temperature-sensor", "Model" : "SEN-TEMP", "Name" : "온도센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "2": { "Class" : "sensor", "Type" : "humidity-sensor", "Model" : "SEN-HUM", "Name" : "습도센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "3": { "Class" : "sensor", "Type" : "dewpoint-sensor", "Model" : "SEN-DEW", "Name" : "이슬점센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "4": { "Class" : "sensor", "Type" : "rain-detector", "Model" : "SEN-RAIN-D", "Name" : "감우센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "5": { "Class" : "sensor", "Type" : "cumulative-flow-sensor", "Model" : "SEN-FLOW", "Name" : "누적유량센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } },
    "6": { "Class" : "sensor", "Type" : "rainfall-sensor", "Model" : "SEN-RAIN-G", "Name" : "강우센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "7": { "Class" : "sensor", "Type" : "pyranometer", "Model" : "SEN-RAD", "Name" : "일사센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "8": { "Class" : "sensor", "Type" : "wind-speed-sensor", "Model" : "SEN-WSPEED", "Name" : "풍속센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "9": { "Class" : "sensor", "Type" : "wind-direction-sensor", "Model" : "SEN-WDIR", "Name" : "풍향센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "10": { "Class" : "sensor", "Type" : "voltage-sensor", "Model" : "SEN-VOL", "Name" : "전압센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "11": { "Class" : "sensor", "Type" : "CO2-sensor", "Model" : "SEN-CO2", "Name" : "이산화탄소센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "12": { "Class" : "sensor", "Type" : "EC-sensor", "Model" : "SEN-EC", "Name" : "EC센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "13": { "Class" : "sensor", "Type" : "quantum-sensor", "Model" : "SEN-QUAN", "Name" : "광량자센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "14": { "Class" : "sensor", "Type" : "soil-moisture-sensor", "Model" : "SEN-SMOI", "Name" : "토양함수율센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "15": { "Class" : "sensor", "Type" : "tensiometer", "Model" : "SEN-TEN", "Name" : "토양장력센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "16": { "Class" : "sensor", "Type" : "pH-sensor", "Model" : "SEN-pH", "Name" : "pH센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "17": { "Class" : "sensor", "Type" : "soil-temperature-sensor", "Model" : "SEN-STEMP", "Name" : "지온센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }, 
    "18": { "Class" : "sensor", "Type" : "weight-sensor", "Model" : "SEN-WGT", "Name" : "무게센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } },
    "19": { "Class" : "sensor", "Type" : "low-water-level-detector", "Model" : "SEN-LWL", "Name" : "저수위센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } },
    "20": { "Class" : "sensor", "Type" : "high-temperature-detector", "Model" : "SEN-HTEMP", "Name" : "고온센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } },
    "21": { "Class" : "sensor", "Type" : "watt-hour-meter", "Model" : "SEN-WHM", "Name" : "전력량계", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } },
    "22": { "Class" : "sensor", "Type" : "current-sensor", "Model" : "SEN-CUR", "Name" : "전류센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } },
    "23": { "Class" : "sensor", "Type" : "battery-sensor", "Model" : "SEN-BAT", "Name" : "배터리잔량센서", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } },
    "24": { "Class" : "sensor", "Type" : "event-trigger", "Model" : "SEN-EVT", "Name" : "이벤트발생기", "CommSpec" : { "KS B 7958" : { "read" : { "items": ["status", "value"] } } } }
}
